version: '3'

services:
  traefik:
    image: traefik:v2.4
    command:
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --api.dashboard=true
    ports:
      - "80:80"
      - "8080:8080"  # Optional: For Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  db:
    image: mariadb:10
    env_file:
      - db.env
    volumes:
      - /zata/public_html_atlas/01_dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - web

  www:
    build: .
    depends_on:
      - db
    volumes:
      - /zata/public_html_atlas/tcr_structure_database.tar.gz:/var/www/html/web/tables/tcr_structure_database.tar.gz:ro
      - ./.mysqlpw.txt:/run/secrets/atlas_db_user_passwd:ro
    labels:
      - "traefik.http.routers.www.rule=PathPrefix(`/`)"
      - "traefik.http.services.www.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
